<?php
/**
 * @file
 */
// $id

/**
 * Implementation of hook_menu().
 */
function renren_comment_menu() {
  return array(
    'admin/settings/renren_connect/comment' => array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('renren_comment_settings_form'),
      'access arguments' => array('admin comment share type with renren'),
      'page title' => t('Select the type that user can share with renren'),
    ),
  );
}

/**
 * Implementation of hook_form_alter().
 */
function renren_comment_form_alter(&$form, &$form_state, $form_id) {
  $node = node_load($form['nid']['#value']);
  $allow_types = variable_get('renren_enable_types', array());
  if (renren_user_is_logined_in() && user_access('share comment with renren') && renren_client() && isset($allow_types[$node->type])) {
    if ($form_id == 'comment_form') {
      $form['renren'] = array(
        '#type' => 'fieldset',
        '#title' => t('Send Renren'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );
      $form['renren']['renren_comment'] = array(
        '#type' => 'textarea',
        '#title' => t('Text'),
      );
      $form['#submit'][] = 'renren_comment_form_submit';
    } 
  }
}

/**
 * Submit hanlder for renren comment
 */
function renren_comment_form_submit($form, $form_state) {
  if ($node) {
    global $user;
      require_once drupal_get_path('module', 'renren') . '/renren.inc';
      if ($form_state['values']['renren_comment']) {
        $response = renren_publish_seed($form_state['values']['renren_comment']);
        dpm($response);
        if ($response->error_code) {
          drupal_set_message(t('Sorry, there have error with Renren APP settings. Please contact site administrator to fix it.'), 'error');
        } 
      }
  }
}

/**
 * Implementation of hook_perm().
 */
function renren_comment_perm() {
  return array('admin comment share type with renren', 'share comment with renren');
}

/**
 * Settings form for comment share with renren
 */
function renren_comment_settings_form(&$form_state) {
  $form = array();
    // comments
  $forms['renren_settings']['renren_comment'] = array(
    '#type' => 'fieldset',
    '#title' => t('Choose and select renren comment settings'),
  );
  $forms['renren_settings']['renren_comment']['renren_enable_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Choose and select renren comment settings'),
    '#options' => node_get_types('names'),
    '#default_value' => variable_get('renren_enable_types', array()),
  );
  return system_settings_form($forms);
}